settings:
  title: 'Status Page'
  url: 'https://status.seanbehan.ca' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: seanbehan-ca
    name: seanbehan.ca
    url: 'https://seanbehan.ca'

  - id: pb-sbehan-ca
    name: pb.sbehan.ca
    url: 'https://pb.sbehan.ca'
